### ISSUE TITLE
Values do not update

### ISSUE THREAD

**Issue by rickAllDev** [jgromes/RohmMultiSensor#3]
Testing communications with BH1745NUC. I can successfully scan sensor, read part id and read mft id. When I read color data I get an initial set of values. These do not change on successive read or after power cycle. Do you have any idea on what might be going on?

I've got a couple of different sensors and getting same data from both

**Comment by jgromes** [comment]
I wasn't able to reproduce this issue with the current version of the library. What Arduino are you using? You could try running ROHM example code, to see if that leads to the same issue.

**Comment by rickAllDev** [comment]
thanks for taking a look at it. I am using a mega 2560. Which ROHM example code are you referring to?

**Comment by jgromes** [comment]
I'm referring to the example code provided for the sensor by ROHM. You can download it [here](http://micro.rohm.com/en/download_support/sensor_module/kiyaku.php?file=data/software/BH1745NUC.zip). Try uploading it and see if the issue still persists.

**Comment by rickAllDev** [comment]
Got it working. Have a few sensors on the i2c bus that were all working fine with the exception of the BH1745NUC. My assumption was that it would not be a wiring issue given everything that was working. I was wrong. I put the BH1745NUC on its own circuit and now I am communicating with it just fine. Don't know what the issue is yet (some combination of resistors and capacitors) but I will figure that out later.

**Comment by jgromes** [comment]
It might be worth looking at the I2C communication with a scope and maybe using stronger pull-ups when there's more sensors on it. Also, try to have the I2C cables as short as possible, since the bus was originally designed for short ranges only. And finally, try to keep the SDA and SCL lines separated and not right next to each other. I've had an issue before with long I2C that was using a ribbon cable with the lines next to each other. Fairly often, voltage changes on SDA induced spikes on SCL, which were then interpreted by the microcontroller as another clock cycle, so the communication started to break down. Anyway, good luck :).
